### ISSUE TITLE
Language version of firmware - concept

### ISSUE THREAD

**Issue by gerwant** [gerwant/flash-wizard#26]
We have to implement choosing a language version of firmware, because some firmwares will be delivered in multiple languages.
There are two concepts to implement such a feature.
By the way, the thing is only about "I don't have .hex file" section.

- First concept - we add one more step on the very beginning, before choosing the device, with language options.
All basing on FTP directory tree, so necessary Assistant mods needed.
- Second concept - similar to the first, also structure of directories needs redesign, but we don't add 5th step. Instead of that, we choose that language which user has selected on the welcome screen. In this case, some warning should be displayed saying that "Don't see the firmware you're looking for? Try choosing English or another language version at the beginning.".

IMO second concept sounds more familiar for our current UI philosophy, less changes need to be done.

**Comment by rafalelo** [comment]
The second concept seems to be better in terms of looks, but IMO it is a bit inconvenient. If there is no firmware in the chosen language,  a user has to go back to the welcome screen, change the language, and then repeat the whole configuration process. Adding some sort of additional step means only two extra clicks. It doesn't have to be a "legit step", it could be some popup, maybe some small icon in the corner or something like that.

On the other hand, if there is the firmware you are looking for, there are no extra steps.

Also, choosing for example English at the beginning, not always means that you want to flash English-language firmware.

**Comment by rafalelo** [comment]
Idk, I prefer some sort of additional step.

**Comment by gerwant** [comment]
As we discussed earlier, some major modifications need to be done.

We will implement choosing the language by showing popup with available languages after clicking sensor. Files will be stored in the server with suffixes like _PL.hex, _EN.hex etc. Furthermore, in popup there will be 9 flags, one per language. Not available options will be grayed out. After clicking the flag, popup closes and according miniature of flag is added next to label "Flash". Clicking such a flag shows popup again.

The plan of work for this concept is following:
- [ ] 🎨  Design the popup
- [ ] 🚧   Show popup after choosing sensor with dummy data
- [ ] 🚸  Display flag next to "Flash" label after choosing language 
- [ ] 💫 Make it interactive - click event causes popup to show again
- [ ] ⬆️ Upload new dummy (or not) firmwares with proper names to the server
- [ ] 🏗️  Restructure API of Assistant
- [ ] 🧙‍♂️ Apply appropriate HTTP calls to the API in Wizard.
- [ ] 🥅 Handle request errors
- [ ] 👨‍💻 Modify popup according to the result of API response. Basing on internal object structure?

- [X] ➕  That's gonna be added to the milestone of v0.1.0 version endgame.
